In [4]:
%load_ext autoreload
%autoreload 2
import os 
import numpy as np
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
os.chdir('..')

In [7]:
from src.models.light_gbm import LightGbmModel


ModuleNotFoundError: No module named 'lightgbm'

In [8]:
lbm = LightGbmModel()

NameError: name 'LightGbmModel' is not defined

In [11]:
lbm.X_train.shape

(4757, 13)

In [12]:
lbm.y_train.shape

(4757, 1)

In [13]:
np.unique(lbm.y_train.round())

array([0, 1])

In [14]:
lbm.y_train.groupby(0).count()

Empty DataFrame
Columns: []
Index: [0, 1]

In [15]:
pd.DataFrame(lbm.y_train).shape

(4757, 1)

In [16]:
model = LightGbmModel()
model.cross_validation()

2019-11-15 21:03:25,805 - src.models.light_gbm - INFO - X_train shape: (4757, 13)
2019-11-15 21:03:25,815 - src.models.light_gbm - INFO - y_train shape: (4757, 1)
2019-11-15 21:03:25,818 - src.models.light_gbm - INFO - x_test shape: (1001, 13)


UNIQUE: Empty DataFrame
Columns: []
Index: [0, 1]


/home/sandro/.local/share/virtualenvs/data_science_for_business_lmu-1wV0OWeh/lib/python3.7/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/sandro/.local/share/virtualenvs/data_science_for_business_lmu-1wV0OWeh/lib/python3.7/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Training until validation scores don't improve for 150 rounds
[250]	training's binary_logloss: 0.195206	valid_1's binary_logloss: 0.371025
Early stopping, best iteration is:
[200]	training's binary_logloss: 0.21775	valid_1's binary_logloss: 0.369539


2019-11-15 21:03:29,323 - src.models.light_gbm - INFO - unique elements: [0. 1.]: counts_elements: [4745   12]


Fold  1 mcc : 0.060977
Training until validation scores don't improve for 150 rounds
[250]	training's binary_logloss: 0.197134	valid_1's binary_logloss: 0.357679
Early stopping, best iteration is:
[342]	training's binary_logloss: 0.167002	valid_1's binary_logloss: 0.356181


2019-11-15 21:03:32,393 - src.models.light_gbm - INFO - unique elements: [0. 1.]: counts_elements: [4721   36]


Fold  2 mcc : 0.124971
Training until validation scores don't improve for 150 rounds
[250]	training's binary_logloss: 0.195813	valid_1's binary_logloss: 0.3702


2019-11-15 21:03:34,227 - src.models.light_gbm - INFO - unique elements: [0. 1.]: counts_elements: [4715   42]


Early stopping, best iteration is:
[163]	training's binary_logloss: 0.238627	valid_1's binary_logloss: 0.368058
Fold  3 mcc : 0.043320
Training until validation scores don't improve for 150 rounds
[250]	training's binary_logloss: 0.202345	valid_1's binary_logloss: 0.355748


2019-11-15 21:03:36,162 - src.models.light_gbm - INFO - unique elements: [0. 1.]: counts_elements: [4702   55]


Early stopping, best iteration is:
[198]	training's binary_logloss: 0.22452	valid_1's binary_logloss: 0.355
Fold  4 mcc : 0.081248
Training until validation scores don't improve for 150 rounds
[250]	training's binary_logloss: 0.196606	valid_1's binary_logloss: 0.363794
Early stopping, best iteration is:
[280]	training's binary_logloss: 0.18595	valid_1's binary_logloss: 0.363271


2019-11-15 21:03:38,385 - src.models.light_gbm - INFO - unique elements: [0. 1.]: counts_elements: [4684   73]


Fold  5 mcc : 0.053471


In [19]:
np.unique(model.sub_preds_abs, return_counts=True)

(array([0., 1.]), array([987,  14]))

In [25]:
model.test_ids.values.transpose()

array([   1,    2,    3, ...,  999, 1000, 1001])

In [29]:
df_submission = pd.DataFrame([model.test_ids.values, model.sub_preds_abs]).transpose()

In [30]:
df_submission.columns=['OBS_ID', 'success']

In [35]:
df_submission['OBS_ID']=df_submission.OBS_ID.astype(int)

In [37]:
df_submission['success'] = df_submission.success.astype(int)

In [38]:
df_submission.to_csv('data/submissions/submission06.csv',index=None)

In [8]:
from sklearn.model_selection import KFold


In [9]:
folds = KFold(n_splits=5, shuffle=True, random_state=123)

In [15]:
oof_preds = np.zeros(lbm.X_train.shape[0])
sub_preds = np.zeros(lbm.X_test.shape[0])

In [18]:
oof_preds.shape

(4757,)

In [19]:
sub_preds.shape

(1001,)

In [23]:
for n_fold, (trn_idx, val_idx) in enumerate(folds.split(lbm.X_train)):
    print(n_fold)
    print(len(trn_idx))
    print(len(val_idx))
    print("==========================")

0
3805
952
1
3805
952
2
3806
951
3
3806
951
4
3806
951


In [27]:
for n_fold, (trn_idx, val_idx) in enumerate(folds.split(lbm.X_train)):
    print(trn_idx)
    trn_x, trn_y = lbm.X_train.iloc[trn_idx], lbm.y_train.iloc[trn_idx]
    val_x, val_y = lbm.X_train.iloc[val_idx], lbm.y_train.iloc[val_idx]


[   0    1    2 ... 4754 4755 4756]


IndexError: positional indexers are out-of-bounds

In [29]:
len(trn_idx)

3805

In [30]:
lbm.X_train.iloc[trn_idx]

transaction_count   holder_count  market_data_current_price_usd  ...  labels_ico_data_hardcap_currency  labels_ico_data_softcap_currency  labels_ico_data_total_raised_currency
0          48262.141038   13576.305982                   1.676610e-03  ...                                23                                15                                      7
1         975773.000000  109840.000000                   2.315610e-01  ...                                23                                15                                     10
2          22730.000000   13914.000000                   7.173600e-04  ...                                14                                 8                                     10
3            125.000000      51.000000                   3.360274e-02  ...                                23                                15                                      7
5          14377.000000    4396.000000                   1.345523e-02  ...                                23                                15                                      7
...                 ...            ...                            ...  ...                               ...                               ...                                    ...
4752       16776.000000    4829.000000                   2.988830e-03  ...                                23                                15                                      7
4753       48262.141038   13576.305982                   1.745867e-02  ...                                23                                15                                      7
4754       48262.141038   13576.305982                   8.420000e-02  ...                                23                                15                                      7
4755         168.000000      34.000000                   6.000000e-07  ...                                23                                15                                      7
4756       48262.141038   13576.305982                   3.400000e-02  ...                                23                                15                                      7

[3805 rows x 13 columns]

In [32]:
lbm.y_train.shape

(4756, 1)

In [35]:
trn_idx

array([   0,    1,    2, ..., 4754, 4755, 4756])

In [39]:
len(lbm.X_train)

4757

In [38]:
len(lbm.y_train)

4756

In [43]:
lbm.X_train

transaction_count   holder_count  market_data_current_price_usd  ...  labels_ico_data_hardcap_currency  labels_ico_data_softcap_currency  labels_ico_data_total_raised_currency
0          48262.141038   13576.305982                   1.676610e-03  ...                                23                                15                                      7
1         975773.000000  109840.000000                   2.315610e-01  ...                                23                                15                                     10
2          22730.000000   13914.000000                   7.173600e-04  ...                                14                                 8                                     10
3            125.000000      51.000000                   3.360274e-02  ...                                23                                15                                      7
4          16417.000000    6250.000000                   8.870100e-04  ...                                23                                15                                      7
...                 ...            ...                            ...  ...                               ...                               ...                                    ...
4752       16776.000000    4829.000000                   2.988830e-03  ...                                23                                15                                      7
4753       48262.141038   13576.305982                   1.745867e-02  ...                                23                                15                                      7
4754       48262.141038   13576.305982                   8.420000e-02  ...                                23                                15                                      7
4755         168.000000      34.000000                   6.000000e-07  ...                                23                                15                                      7
4756       48262.141038   13576.305982                   3.400000e-02  ...                                23                                15                                      7

[4757 rows x 13 columns]

In [30]:
from src.features.feature_class import FeatureEngineering
from src.features.utils import read_processed_data


In [31]:
df_bitcoin, df, df_test = read_processed_data()

2019-11-15 19:43:47,877 - src.features.utils - INFO - Shape of df_bitcoin: (2355, 1)
2019-11-15 19:43:47,878 - src.features.utils - INFO - Shape of df: (4757, 92)


In [32]:
fe = FeatureEngineering(df, df_bitcoin, df_test)

/c/Users/Sandro/repo/data_science_for_business_lmu/src/features/feature_class.py:29: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  self.df = pd.concat([df, df_test])


In [33]:
fe.construct_features()

2019-11-15 19:43:49,594 - src.features.feature_class - INFO - Transform numerical variable for column transaction_count
2019-11-15 19:43:49,596 - src.features.feature_class - INFO - Start filling NA values in transaction_count
2019-11-15 19:43:49,603 - src.features.feature_class - INFO - Found 2695 NA values in column transaction_count
2019-11-15 19:43:49,605 - src.features.feature_class - INFO - Filled NA values
2019-11-15 19:43:49,618 - src.features.feature_class - INFO - Transform numerical variable for column holder_count
2019-11-15 19:43:49,619 - src.features.feature_class - INFO - Start filling NA values in holder_count
2019-11-15 19:43:49,626 - src.features.feature_class - INFO - Found 2699 NA values in column holder_count
2019-11-15 19:43:49,628 - src.features.feature_class - INFO - Filled NA values
2019-11-15 19:43:49,646 - src.features.feature_class - INFO - Transform numerical variable for column market_data_current_price_usd
2019-11-15 19:43:49,648 - src.features.feature_cl

In [34]:
X_train, y_train, X_test = fe.get_X_y()

2019-11-15 19:43:52,833 - src.features.feature_class - INFO - DF_train shape: (4757, 15)
2019-11-15 19:43:52,839 - src.features.feature_class - INFO - df_test shape: (4757, 15)
2019-11-15 19:43:52,844 - src.features.feature_class - INFO - X_train shape: (4757, 13)
2019-11-15 19:43:52,846 - src.features.feature_class - INFO - y_train shape: (4757,)
2019-11-15 19:43:52,848 - src.features.feature_class - INFO - X_test shape: (1001, 14)


In [56]:
y_train.shape

(4757,)

In [60]:
y_train = y_train.values.astype(int)

In [64]:
y_train.tofile('data/features/features_y_train')

In [67]:
np.fromfile('data/features/features_y_train', dtype=int)

array([0, 1, 0, ..., 0, 0, 0])

In [53]:
y_train.to_csv('data/features/features_y_train.csv', index=False, encoding="utf-8")

/home/sandro/.local/share/virtualenvs/data_science_for_business_lmu-1wV0OWeh/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.


In [54]:
import pandas as pd

In [55]:
pd.read_csv('data/features/features_y_train.csv').shape

(4756, 1)